#!/bin/bash
# Gulf Watch Deployment Helper

echo "========================================"
echo "  Gulf Watch - Deployment Checklist"
echo "========================================"
echo ""
echo "Step 1: Render (Backend + Database)"
echo "------------------------------------"
echo "1. Go to: https://dashboard.render.com"
echo "2. New → PostgreSQL → Name: gulf-watch-db"
echo "3. New → Web Service → Connect GitHub"
echo "4. Root: backend, Build: pip install -r requirements.txt"
echo "5. Start: python -m uvicorn src.api_v2:app --host 0.0.0.0 --port \$PORT"
echo "6. Add DATABASE_URL env var"
echo ""
echo "Step 2: Vercel (Frontend)"
echo "--------------------------"
echo "1. Go to: https://vercel.com"
echo "2. Add New Project → Import GitHub"
echo "3. Framework: Vite, Root: frontend"
echo "4. Add VITE_API_URL = https://gulf-watch-api.onrender.com"
echo ""
echo "Step 3: Test URLs"
echo "------------------"
echo "Backend: https://gulf-watch-api.onrender.com"
echo "Frontend: https://gulf-watch.vercel.app"
echo ""
